### ISSUE TITLE
Doesn't appear to work with Webpack

### ISSUE THREAD

**Issue by brins0** [stephenwvickers/node-raw-socket#13]
When attempting to bundle in a module which references `raw-socket` (such as `net-ping`), I get the following error when using `net-ping@1.2.0` which has a dependency on `raw-socket@*` (resolving to 1.4.0):

```
ERROR in ./~/raw-socket/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./build/Release/raw in /data/Services/brins0.home/node_modules/raw-socket
     @ ./~/raw-socket/index.js 4:10-41
```

I'm using `webpack@1.12.14` for the bundle generation, and running it on a Ubuntu 15.10 machine with node v5.3.0.

Other modules pack in fine but all other modules with a dependency on `raw-socket` which I have tried fail in the same way.

**Comment by kibs** [comment]
I don't think using node-ping in a webbrowser would work. Why do you try to build it using webpack?

**Comment by brins0** [comment]
I'm using webpack to build a single distributable which I can dump on a pi or emote server without having to install loads of modules. It'll save a fair amount of time doing it like that for multiple units. I plan on pinging the same node from different networks and collating the results, so I need to be able to spin up a new instance of it easily.

**Comment by kibs** [comment]
cool! but i don't think you will get webpack to compile this, as node-raw-socket builds some C code. What  you could be looking at is eg. docker, so you run docker on the PI's, and build docker images and push them

**Comment by brins0** [comment]
Ah, that'll likely be why I'm seeing binaries there and getting confused by them then! Is there a way of using the built in node stuff for sending packets in the same way? I'm not 100% sure what's required for ICMP compared to normal stuff. I've faffed around with sending UDP/TCP traffic before to interface with other network hardware, but nothing as low level as ICMP.

I also forgot to mention that I'm using some ES2015/ES6 code which is being run through babel so that's the other reason I'm using webpack.

**Comment by kibs** [comment]
i think it is needed, but i am not the author. You don't need webpack to run babel though. You could just setup and run babel on your code.

**Comment by stephenwvickers** [comment]
Hi, the module has not been tested to work with webpack, I also have no experience with it.

I don't mind supporting it but you'll need to supply a patch if you want it supported.
