### ISSUE TITLE
Can be used for IPC? :D

### ISSUE THREAD

**Issue by Dillybob92** [stephenwvickers/node-raw-socket#18]
Hey guys,

Just curious... I have 3 node processes and was curious if raw-socket would be good for IPC. I am using the processes for game instances for my Diablo 2 style game.  

When players join the load balancer they get put on a random node (to help scale nodejs) -- but when they move around in the game I need to send messages through IPC.  

I was wondering would this module be the right solution for this, or node-ipc? Would there ever be a bottleneck if using raw-socket? Thanks

**Comment by stephenwvickers** [comment]
Hi,

Did you create a ticket under the right project?

I'm not sure if this relates to the raw-socket module.

Steve

**Comment by Dillybob92** [comment]
Sorry yeah
