### ISSUE TITLE
This is not a issues, could set a localAddress when do CreateSocket() in options

### ISSUE THREAD

**Issue by vpnemail** [stephenwvickers/node-raw-socket#20]
Hi Stephenwvickers,
Thank you for your great project. It really help our project.
I have a problem when I use node-raw-socket.
I need assign localAddress in socket's header before send or listen the localAddress.
Because my eth0 have 2 or more ip4 address.
I want raw-socket can specific a ip from eth0's ip4 group.
if raw-socket can add a option like:
var options = {
    addressFamily: raw.AddressFamily.IPv4,
    protocol: raw.Protocol.None,
    bufferSize: 4096,
    generateChecksums: false,
    checksumOffset: 0
    localAddress: '192.168.0.1'
};
if have localAddress
raw-socket will listen only for localAddress and send socket use the localAddress in socket header.

Thank you so much

Peter

**Comment by vpnemail** [comment]
Hi Stephenwvickers,

I find a way for clear my problem.
I use socket.setOption to bind the network interface before send pocket.
`socket.setOption (raw.SocketLevel.SOL_SOCKET, raw.SocketOption.SO_BINDTODEVICE, new Buffer (interfaceName), interfaceName.length)`
It looks working perfect.

Thank you.

Peter

**Comment by stephenwvickers** [comment]
Thanks for the update.

**Comment by sky37042** [comment]
Hello,

Let interfaceName is 'eth1:1', but it will show 'Error: No such device'.

How to fix it problem ?

Thanks

**Comment by vpnemail** [comment]
Hi

You looks used a vlan interface.
The raw-socket looks can't reach a alias of interface.
If need use vlan may be the veth peer vlan is good solution.
this link have more detail:
[http://superuser.com/questions/764986/howto-setup-a-veth-virtual-network](url)

Peter

**Comment by stephenwvickers** [comment]
HI,

It is unclear to me what the problem is - I don't understand where you provide `interfaceName` for example.

Can you provide example code that emits the issue, and how you run the code?

Thanks

Steve
