### ISSUE TITLE
Add link to solution of "Operation not permitted" exception

### ISSUE THREAD

**Issue by nevmerzhitsky** [stephenwvickers/node-raw-socket#21]
Hi, Stephen!

You can add link to http://blog.fpmurphy.com/2009/05/linux-security-capabilities.html article to the second paragraph of https://github.com/steffengy/node-raw-socket#raw-socket-behaviour to help your users solve this issue without taking superuser privileges. Or copy my own instruction about this https://github.com/nevmerzhitsky/node-ping-scheduler#troubleshooting.

**Comment by stephenwvickers** [comment]
Hi, thank you for the suggestion but this is very Linux specific.  The section you pointed out already states that privileged access may be required.  I would rather users fully understand how raw sockets work before using them, this is very important.
