### ISSUE TITLE
How to set outgoing IP  ?

### ISSUE THREAD

**Issue by sky37042** [stephenwvickers/node-raw-socket#22]
Hello,

The server is configured with multiple IP, how to specify an IP as the outgoing IP?

Thanks

**Comment by stephenwvickers** [comment]
I believe you will have several options.

1) Use the IP_HDRINCL socket option and provide your own IP header - using the desired source address
2) Use the SO_BINDTODEVICE socket option and specify the network interface to bind to - you will have to test this
3) Add a static route to the routing table

Steve
