### ISSUE TITLE
Pre built binaries

### ISSUE THREAD

**Issue by colthreepv** [stephenwvickers/node-raw-socket#24]
I know that native node.js modules are tedious, altough adoption is very low without pre-built binaries, so I would ask for that

**Comment by stephenwvickers** [comment]
Hi,

I have no plans to release pre-built binaries.

There are too many variables to be able to provide stable binaries for all supported platforms.

Steve

**Comment by colthreepv** [comment]
I did a prototype fork with appveyor to create a winx64 build (I think the most complicate platform)
https://github.com/colthreepv/node-raw-socket/releases/tag/1.5.1

If you might accept me as collaborator I can try creating different builds for node 4.x ABI and node 6.x for windows/linux/darwin platforms

**Comment by stephenwvickers** [comment]
Hi, as I previously said, there are too many variables to be able to provide stable binaries for all supported platforms, including for whenever new node versions are released across all the platforms.

Steve
