### ISSUE TITLE
IP_HDRINCL on macOS

### ISSUE THREAD

**Issue by latysheff** [stephenwvickers/node-raw-socket#26]
On macOS attempt to send a packet with activated IP_HDRINCL socket option fails with Error: Invalid argument

**Comment by stephenwvickers** [comment]
Hi,

Can you please provide example code that fails.

Thanks

Steve

**Comment by latysheff** [comment]
Hi Steve,

I took example from this repo, ping-no-ip-header.js, and updated ip addresses to mine.
But I've found the solution: "for Sendto OS X/BSD want the IP length in host byte order" http://stackoverflow.com/questions/32575558/creating-raw-packets-with-go-1-5-on-macosx. On macOS little endian seems to be the case, so in ping example one need to update packet length field like this: `buffer.writeUInt16LE(60,2)`
