### ISSUE TITLE
Not able to install module Ubuntu 16.04 Node 6.11

### ISSUE THREAD

**Issue by RomanBurunkov** [stephenwvickers/node-raw-socket#31]
Hi,
I've got this:

> 172 error Linux 4.4.0-83-generic
> 173 error argv "/root/.nvm/versions/node/v6.11.0/bin/node" "/root/.nvm/versions/node/v6.11.0/bin/npm" "install"
> 174 error node v6.11.0
> 175 error npm  v3.10.10
> 176 error code ELIFECYCLE
> 177 error raw-socket@1.5.1 install: `node-gyp rebuild`
> 177 error Exit status 126
> 178 error Failed at the raw-socket@1.5.1 install script 'node-gyp rebuild'.
> 178 error Make sure you have the latest version of node.js and npm installed.
> 178 error If you do, this is most likely a problem with the raw-socket package,
> 178 error not with npm itself.
> 178 error Tell the author that this fails on your system:
> 178 error     node-gyp rebuild
> 178 error You can get information on how to open an issue for this project with:
> 178 error     npm bugs raw-socket
> 178 error Or if that isn't available, you can get their info via:
> 178 error     npm owner ls raw-socket
> 178 error There is likely additional logging output above.
> 179 verbose exit [ 1, true ]
> 

Can build it manually from github, but npm throws error.

**Comment by stephenwvickers** [comment]
What is your version of Python?

**Comment by RomanBurunkov** [comment]
@stephenwvickers,

It is 2.7

**Comment by stephenwvickers** [comment]
Please can you send through the npm-debug.log file?

**Comment by daverickdunn** [comment]
Howdy,

I've had the same, or at least similar, issue on Windows 10.

Also, possibly related, earlier this morning it also refused to build when installing on Debian, in that case the issue was caused by using the **--production** flag with **npm install**. 

i.e.
`npm install --production`

Not sure if this is expected behaviour when using **--production**, but I assume not...

Log:

[npm-debug.txt](https://github.com/stephenwvickers/node-raw-socket/files/1197292/npm-debug.txt)

Msg:

```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.5.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\web-tools\npm-debug.log
```

Cheers,
Rich

**Comment by daverickdunn** [comment]
Just updated my node and NPM, (yeah I know, probably should have started there in the first place...), still no joy unfortunately, but now there's new errors.

Node: 6.10.3
NPM: 5.3.0

Don't say I'm not good to you: 

[2017-08-03T13_31_56_462Z-debug.txt](https://github.com/stephenwvickers/node-raw-socket/files/1197341/2017-08-03T13_31_56_462Z-debug.txt)


```
C:\Users\Richard\AppData\Roaming\npm\grunt -> C:\Users\Richard\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
+ grunt-cli@1.2.0
updated 15 packages in 2.5s

> raw-socket@1.5.1 install C:\dev\web-tools\node_modules\raw-socket
> node-gyp rebuild


C:\dev\web-tools\node_modules\raw-socket>if not defined npm_config_node_gyp (node "C:\Users\Richard\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\dev\web-tools\node_modules\raw-socket\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Richard\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Richard\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\web-tools\node_modules\raw-socket
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN lightnet-web-tools@0.0.1 No repository field.
npm WARN lightnet-web-tools@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-socket@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Richard\AppData\Roaming\npm-cache\_logs\2017-08-03T13_31_56_462Z-debug.log
```

**Comment by daverickdunn** [comment]
Ok, I have a workaround for Windows (If anyone else has problems):

Follow option 2 instructions here: [node-gyp install instructions](https://github.com/nodejs/node-gyp#option-2)

However, **node-gyp** wouldn't pick up the `npm config set msvs_version 2015` for me, even when set to global: `npm config set msvs_version 2015 --global`

So this still errors out, and the latest version of npm rolls back, meaning the raw-socket folder isn't left behind after an `NPM install`

So I install raw-socket separately from the rest of my packages, and I add the ignore scripts flag to prevent the build failure that causes the rollback: `npm install raw-socket --ignore-scripts`

Then I navigate to the raw-socket folder: `node_modules/raw-socket` and from here do a rebuild manually, however, as I said above, **node-gyp** doesn't pick up `npm config set msvs_version 2015` for some reason, but it _does_ work if it's passed as a param: `node-gyp rebuild --msvs_version=2015`

Boom! 

(I had follow these steps twice, on two machines, so they should be fairly solid, but ymmv)

**Comment by stephenwvickers** [comment]
Thanks for info, I've had similar issues in the past.  Does this work for you at all:

```
npm install --msvs_version=2015
```

Or:

```
npm install --msvs_version=2015 raw-socket
```

Steve

**Comment by daverickdunn** [comment]
Hi Steve,

Yeah that works as well. 

Only thing to note is that it warns about some type conversion methods in _raw.cc_ - `ToInt32` and `ToUint32` - being depreciated. 

Cheers,
Rich

**Comment by stephenwvickers** [comment]
That's something I've always wanted to get round to addressing. Could I ask you open a ticket for it and I will get it addressed? Many thanks.
