### ISSUE TITLE
Promiscuous mode

### ISSUE THREAD

**Issue by danlobo** [stephenwvickers/node-raw-socket#37]
Hi,

The use case is, I'm developing an app to communicate with some specific appliances which can or cannot have an IP address (so the srcIp is 0.0.0.0, the mac is the ethernet port mac address of the appliance). In this case, the communication is established using raw sockets, but with sockets set on promiscuous mode.

Is it feasible to put this feature in this Node.js module, since we are working with raw sockets?

I have a C# working application, and planning to develop a solution in Node.js and raw-socket for linux too.

Attached is a packet sniffing to demonstrate the issue.

Thanks in advance.
![mactelnet](https://user-images.githubusercontent.com/3091181/30133487-7185a2c4-932a-11e7-9e62-7adee5b1d1c4.png)

**Comment by danlobo** [comment]
Ignore it, tested on Windows and data was received as expected, on linux it didn't, though. Will do more tests.

**Comment by stephenwvickers** [comment]
Thanks for the update.

Perhaps you could try putting the interface into promiscuous mode on Linux, you may then see the return packets, maybe either of these would work:

```
ifconfig eth1 promisc

ip link set eth1 promisc on
```

I have no idea if this will work, it's just a thought that comes to mind.
