### ISSUE TITLE
Utf8String compilation errors when using node 0.10.x

### ISSUE THREAD

**Issue by exmac** [stephenwvickers/node-raw-socket#6]
after last update: 
npm install 

  CXX(target) Release/obj.target/raw/src/raw.o
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::Send(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:662:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (args[3]);
   ^
../src/raw.cc:662:22: error: expected ‘;’ before ‘address’
   String::Utf8String address (args[3]);
                      ^
../src/raw.cc:663:44: error: ‘address’ was not declared in this scope
   struct sockaddr_in6 addr = uv_ip6_addr (*address, 0);
                                            ^
../src/raw.cc:673:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (info[3]);
   ^
../src/raw.cc:673:22: error: expected ‘;’ before ‘address’
   String::Utf8String address (info[3]);
                      ^
../src/raw.cc:674:43: error: ‘address’ was not declared in this scope
   struct sockaddr_in addr = uv_ip4_addr (*address, 0);
                                           ^
make: *** [Release/obj.target/raw/src/raw.o] Error 1

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28

**Comment by stephenwvickers** [comment]
Hi,

The most recent version of raw-socket was tested on 0.12 and 4.0 only.

Can you please try a newer version node, if possible?

If not, please let me know and I will look further.

Thanks

Steve

**Comment by exmac** [comment]
hi,

i checked on 4.0, work ok, 
you don't want to support 0.10 for next versions of raw-socket ?

thanks.

**Comment by stephenwvickers** [comment]
Hi,

It's not that I don't want to support 0.10, I just have limited time right now :(

Steve

**Comment by exmac** [comment]
ok, i will try to migrate to node 4.0 in our projects.

thanks for great project.

**Comment by stephenwvickers** [comment]
Thanks, if you still need help with this just re-open the issue.

Steve
