### ISSUE TITLE
can not install !! how to manual?

### ISSUE THREAD

**Issue by zhaowenjian** [stephenwvickers/node-raw-socket#8]
foreve_@zhao-VostroPC:~/workspace/ipTrafficMonitor$ npm install raw-socket
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "raw-socket"
npm ERR! node v6.0.0-pre
npm ERR! npm  v3.3.6
npm ERR! path /home/foreve_/workspace/ipTrafficMonitor/node_modules/node-raw-socket
npm ERR! code EISGIT

npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     /home/foreve_/workspace/ipTrafficMonitor/node_modules/node-raw-socket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/foreve_/workspace/ipTrafficMonitor/npm-debug.log
foreve_@zhao-VostroPC:~/workspace/ipTrafficMonitor$ ^C
foreve_@zhao-VostroPC:~/workspace/ipTrafficMonitor$ npm install raw-socket

> raw-socket@1.4.0 install /home/foreve_/workspace/ipTrafficMonitor/node_modules/raw-socket
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.2.0-16-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/foreve_/workspace/ipTrafficMonitor/node_modules/raw-socket
gyp ERR! node -v v6.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON /home/foreve_/workspace/ipTrafficMonitor No description
npm WARN EPACKAGEJSON /home/foreve_/workspace/ipTrafficMonitor No repository field.
npm WARN EPACKAGEJSON /home/foreve_/workspace/ipTrafficMonitor No license field.
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "raw-socket"
npm ERR! node v6.0.0-pre
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/foreve_/workspace/ipTrafficMonitor/npm-debug.log

**Comment by stephenwvickers** [comment]
Hi,

I believe your installation issue relates to this error:

gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead

You should address that issue before attempting to install this module.

Steve

**Comment by zhaowenjian** [comment]
Thanks stephenwvickers . When i use node v5.0&npm v3.3(latest version), it point that the gyp-rebuild need python2.7. After python installed , the problem solved.
