### ISSUE TITLE
Select outgoing address or interface

### ISSUE THREAD

**Issue by zachary822** [stephenwvickers/node-raw-socket#9]
Would it be possible to select outgoing interface or source address? If yes, how?

**Comment by stephenwvickers** [comment]
Hi,

If you are running Linux you can use the `SO_BINDTODEVICE` socket option:

```javascript
socket.setOption(raw.SocketLevel. SOL_SOCKET, raw.SocketOption.SO_BINDTODEVICE, ...);
```

For Windows I am not sure their is an equivalent.

Other than that you could try to do something with your local routing table.

Steve
